let myString = "AaBbcdefG123!234%^&*";
let atozSmall =/[a-z]/g;
let NotAtozSmall =/[^a-z]/g;
let atozCapital =/[A-Z]/g;
let NotAtozCapital =/[^A-Z]/g;
let aAndcAnde = /a|c|e/g;
let NotaAndcAnde =/[^a c e]/g;
let lettersCapsAndSmall = /[a-z A-Z]/g;
let numsAndSpecials =/[^a-zA-Z]/g;
let specials =/[^a-z 1-9]/ig;
console.log(myString.match(atozSmall));
console.log(myString.match(NotAtozSmall));
console.log(myString.match(atozCapital));
console.log(myString.match(NotAtozCapital));
console.log(myString.match(aAndcAnde));
console.log(myString.match(NotaAndcAnde));
console.log(myString.match(lettersCapsAndSmall));
console.log(myString.match(numsAndSpecials));
console.log(myString.match(specials));